---
deployment:
  tasks:
    - export REPOPATH=/home/belovezhby/repositories/belovezhby/*
    - export SITEPATH=/home/belovezhby/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH